package com.ecodex.middleware.wsdlautogen;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2024-10-10T21:20:45.093+02:00
 * Generated source version: 3.5.0
 *
 */
@WebServiceClient(name = "SendMessageToMiddlewareCallbackImplService",
                  wsdlLocation = "http://localhost:8081/services/callback?wsdl",
                  targetNamespace = "http://wsclient.callback/job01")
public class SendMessageToMiddlewareCallbackImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://wsclient.callback/job01", "SendMessageToMiddlewareCallbackImplService");
    public final static QName SendMessageToMiddlewareCallbackImplPort = new QName("http://wsclient.callback/job01", "SendMessageToMiddlewareCallbackImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/services/callback?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SendMessageToMiddlewareCallbackImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8081/services/callback?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SendMessageToMiddlewareCallbackImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SendMessageToMiddlewareCallbackImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendMessageToMiddlewareCallbackImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SendMessageToMiddlewareCallbackImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SendMessageToMiddlewareCallbackImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SendMessageToMiddlewareCallbackImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SendMessageToMiddlewareCallbackImpl
     */
    @WebEndpoint(name = "SendMessageToMiddlewareCallbackImplPort")
    public SendMessageToMiddlewareCallbackImpl getSendMessageToMiddlewareCallbackImplPort() {
        return super.getPort(SendMessageToMiddlewareCallbackImplPort, SendMessageToMiddlewareCallbackImpl.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendMessageToMiddlewareCallbackImpl
     */
    @WebEndpoint(name = "SendMessageToMiddlewareCallbackImplPort")
    public SendMessageToMiddlewareCallbackImpl getSendMessageToMiddlewareCallbackImplPort(WebServiceFeature... features) {
        return super.getPort(SendMessageToMiddlewareCallbackImplPort, SendMessageToMiddlewareCallbackImpl.class, features);
    }

}
