package com.ecodex.middleware.wsdlautogen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2024-10-10T21:20:45.052+02:00
 * Generated source version: 3.5.0
 *
 */
@WebService(targetNamespace = "http://wsclient.callback/job01", name = "SendMessageToMiddlewareCallbackImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface SendMessageToMiddlewareCallbackImpl {

    @WebMethod
    @RequestWrapper(localName = "onJobComplete", targetNamespace = "http://wsclient.callback/job01", className = "com.ecodex.middleware.wsdlautogen.OnJobComplete")
    @ResponseWrapper(localName = "onJobCompleteResponse", targetNamespace = "http://wsclient.callback/job01", className = "com.ecodex.middleware.wsdlautogen.OnJobCompleteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String onJobComplete(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "processCallback", targetNamespace = "http://wsclient.callback/job01", className = "com.ecodex.middleware.wsdlautogen.ProcessCallback")
    @ResponseWrapper(localName = "processCallbackResponse", targetNamespace = "http://wsclient.callback/job01", className = "com.ecodex.middleware.wsdlautogen.ProcessCallbackResponse")
    public void processCallback(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
